# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2

jobs:
  build:
    steps:
      - checkout
      # ssh://codeserver.dev.53ca31b2-20d6-4710-9e4f-ff1f750f4219@codeserver.dev.53ca31b2-20d6-4710-9e4f-ff1f750f4219.drush.in:2222/~/repository.git -b master ret-test
      - run:
          name: Authenticate with Pantheon's CLI using a machine token
          command: terminus -n auth:login --machine-token="$TERMINUS_TOKEN"
      - run:
          name: Checkout site repository from Pantheon
          command: |
            # Ensure that there's a Pantheon repo locally. If one was not
            # restored from cache, clone it fresh.
            git clone https://github.com/oliverfeher/test-ret.git


